task_queue_python = "python-worker-task-queue"
task_queue_polyglot = "task-queue-polyglot"
temporal_server_url = "localhost:7233"
otel_collector_url = "http://localhost:4317"
python_greeting_workflow = "PythonGreetingWorkflow"
go_greeting_workflow = "GoGreetingWorkflow"
python_greeting_activity = "PythonGreetingActivity"
